# Generated by Django 4.0 on 2025-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название локации')),
                ('description_short', models.TextField(verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('coordinates_lng', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Координаты долготы')),
                ('coordinates_lat', models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Координаты широты')),
            ],
        ),
    ]
