# Generated by Django 4.0 on 2025-05-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.location', verbose_name='Локация'),
        ),
    ]
