# Generated by Django 4.2 on 2025-05-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_location_image_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название картинки')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Location_Image',
        ),
        migrations.AddField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.location', verbose_name='Локация'),
        ),
    ]
