# Generated by Django 4.2 on 2025-05-15 13:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_locationimage_alter_location_options_location_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
        migrations.AddField(
            model_name='location',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
