# Generated by Django 4.2 on 2025-05-18 09:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_location_options_remove_location_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='content',
        ),
        migrations.AlterField(
            model_name='location',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
