# Generated by Django 4.2 on 2025-05-23 16:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_location_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinates_lat',
            new_name='lat_coordinates',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='coordinates_lng',
            new_name='lng_coordinates',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='locationimage',
            name='title',
        ),
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.location', verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Поле для сортировки'),
        ),
    ]
