# Generated by Django 4.2 on 2025-05-26 15:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_coordinates_lat_location_lat_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, default=' ', verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название локации'),
        ),
    ]
