# Generated by Django 4.2 on 2025-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_location_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
