# Generated by Django 4.2 on 2025-05-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_locationimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationimage',
            name='title',
        ),
    ]
